apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mymicro
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jacksonitoro/Kubernetes-Microservices-Deployment-with-GitOps
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mymicro
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

